In [1]:
import pandas as pd

In [24]:
print("Reading csv file ")
df=pd.read_csv('labeled_data.txt')
print("\n file reading sucessfully")

Reading csv file

 file reading sucessfully

In [13]:
print("printing top rows ")
df.head()

printing top rows

,Total_votes,hate_speech,offensive_language,neither,class,comments
0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [15]:
print(" dropping or removing  unnamed column name  ")
df=df.drop('Unnamed: 0', axis=1)

df.head()

 dropping or removing  unnamed column name

,count,hate_speech,offensive_language,neither,class,tweet
0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [16]:
print("changing tweet column name to comments")
df.rename(columns={'tweet':'comments'},inplace=True)

changing tweet column name to comments

In [17]:
print("changing count column name to total_votes")
df.rename(columns={'count':'Total_votes'},inplace=True)

changing count column name to total_votes

In [18]:
print("printing the info of the file ")
df.info()

printing the info of the file
<class 'pandas.DataFrame'>
RangeIndex: 24783 entries, 0 to 24782
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Total_votes         24783 non-null  int64
 1   hate_speech         24783 non-null  int64
 2   offensive_language  24783 non-null  int64
 3   neither             24783 non-null  int64
 4   class               24783 non-null  int64
 5   comments            24783 non-null  str
dtypes: int64(5), str(1)
memory usage: 1.1 MB

In [19]:
print("describing the file ")
df.describe()

describing the file

,Total_votes,hate_speech,offensive_language,neither,class
count,24783.000000,24783.000000,24783.000000,24783.000000,24783.000000
mean,3.243473,0.280515,2.413711,0.549247,1.110277
std,0.883060,0.631851,1.399459,1.113299,0.462089
min,3.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,0.000000,2.000000,0.000000,1.000000
50%,3.000000,0.000000,3.000000,0.000000,1.000000
75%,3.000000,0.000000,3.000000,0.000000,1.000000
max,9.000000,7.000000,9.000000,9.000000,2.000000

In [20]:
print("Rows and columns in file are ")
df.shape

Rows and columns in file are

(24783, 6)

In [21]:
print("printing class and comments cloumn ")
df[['class','comments']]

printing class and comments cloumn

       class                                           comments
0          2  !!! RT @mayasolovely: As a woman you shouldn't...
1          1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2          1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3          1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4          1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...      ...                                                ...
24778      1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779      2  you've gone and broke the wrong heart baby, an...
24780      1  young buck wanna eat!!.. dat nigguh like I ain...
24781      1              youu got wild bitches tellin you lies
24782      2  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 2 columns]

In [ ]:

print("Missing Values in Each Column:")
print(df.isnull().sum())


df = df.dropna()

print("\nDataset Shape After Removing Missing Values:")
df.shape

Missing Values in Each Column:
Total_votes           0
hate_speech           0
offensive_language    0
neither               0
class                 0
comments              0
dtype: int64

Dataset Shape After Removing Missing Values:

(24783, 6)

In [23]:

print("Total Duplicate Rows:")
print(df.duplicated().sum())

df = df.drop_duplicates()

print("\nDataset Shape After Removing Duplicates:")
df.shape

print("\nClass Distribution:")
print(df['class'].value_counts())


df.to_csv('cleaned_data.csv', index=False)

print("\nCleaned Dataset Saved Successfully!")

Total Duplicate Rows:
0

Dataset Shape After Removing Duplicates:

Class Distribution:
class
1    19190
2     4163
0     1430
Name: count, dtype: int64

Cleaned Dataset Saved Successfully!